#include <stdio.h>										//Baran Kaya 150130032
#include <stdlib.h>
#include <math.h>

void midprng(long long unsigned int *);
void lsdprng(long long unsigned int *);
void print_histogram(int, int);
int take_samples(int, int *, int *, int *, int *, int*);

int main(){ 
	long long unsigned int seed;
	int selection, num_sample, i;
	int counter1_100 = 0, counter101_200 = 0, counter201_300 = 0, counter301_400 = 0, counter401_500 = 0;
	
	printf("Which PRNG Algorithm?\n\t1.MID-PRNG\n\t2.LSD-PRNG\n\n");
	scanf("%d", &selection);
	puts("");
	
	printf("Enter the seed (5 digits):\n");
	scanf("%llu", &seed);
	puts("");
	
	printf("Enter Number of Samples:\n");
	scanf("%d", &num_sample);
	puts("");
	
		
	if( selection == 1 ){	//MIDPRNG SECIMI																									//MID-PRNG SECIMI
		
		for( i=0; i < num_sample; i++){
			midprng(&seed);
			//printf("%llu\n", seed );      //Çýkan sayýlarý yazdýrma
			
			take_samples(seed, &counter1_100, &counter101_200, &counter201_300, &counter301_400, &counter401_500);		
		}
		
		printf("%d random numbers were generated by using MID-PRNG: \n\n", num_sample);
		
		printf("  1..100: ");
		print_histogram(counter1_100, num_sample);
		printf("101..200: ");
		print_histogram(counter101_200, num_sample);
		printf("201..300: ");
		print_histogram(counter201_300, num_sample);
		printf("301..400: ");
		print_histogram(counter301_400, num_sample);
		printf("401..500: ");
		print_histogram(counter401_500, num_sample);
		
	}
	
	else if( selection == 2 ){	//LSDPRNG SECIMI																								//LSD-PRNG SECIMI
		
		if( seed % 2 == 0 || seed % 5 == 0){		//LSD'DE CIFT YA DA 5'E BOLUNEN ISE
		
			printf("If you want to use LSD-PRNG the seed must be neither even nor ends in a 5.\n");		
			printf("Please try again.\n");
			return 0;
		}
		
		else{		//LSD'DE CIFT YA DA 5'E BOLUNEN DEGIL ISE
			
			for( i=0; i < num_sample; i++){
				lsdprng(&seed);
				//printf("%llu\n", seed );	 //Çýkan sayýlarý yazdýrma
				
				take_samples(seed, &counter1_100, &counter101_200, &counter201_300, &counter301_400, &counter401_500);	
			}
		
		printf("%d random numbers were generated by using LSD-PRNG: \n\n", num_sample);
			
		printf("  1..100: ");
		print_histogram(counter1_100, num_sample);
		printf("101..200: ");
		print_histogram(counter101_200, num_sample);
		printf("201..300: ");
		print_histogram(counter201_300, num_sample);
		printf("301..400: ");
		print_histogram(counter301_400, num_sample);
		printf("401..500: ");
		print_histogram(counter401_500, num_sample);
		
		}
	}
	
	else{		//SECIM 1 YA DA 2 DEGIL ISE																							//SECIM 1 YA DA 2 DEGILSE
		
		printf("Incorrect selection input, please try again...");
		return 0;
	}
}																																	//MAIN SONU



void midprng(long long unsigned int *seed){																							//MID-PRNG FUNC.
		
	if( ( (*seed * *seed ) / 10000000 ) >= 100){				//Eger sayý 10 basamaklý ise
		*seed = ( ( *seed * *seed ) / 1000 ) % 100000;
	}
	
	else if( 10 <= ( (*seed * *seed ) / 10000000 ) < 100){		//Eger sayý 9 basamaklý ise
		*seed = ( ( ( *seed * *seed ) / 100 ) % 100000 );
	}
	
	else if( 1 <= ( (*seed * *seed ) / 10000000 ) < 10){		//Eger sayý 8 basamaklý ise
		*seed = ( ( ( *seed * *seed ) / 10 ) % 100000 );
	}
	
	else if( 0 <= ( (*seed * *seed ) / 10000000 ) < 1){			//Eger sayý 7 basamaklý ise
		*seed = ( ( *seed * *seed ) % 100000 );
	}

}



void lsdprng(long long unsigned int *seed){																							//LSD-PRNG FUNC.
	
	*seed = (*seed * 73 )% 100000;
	
	/*if(*seed / 10000 == 0)					//Ýþlem sonunda 4 basamaklý kaldý ise tekrar 73 ile çarp  (0xxxx)
		*seed = (*seed * 73 )% 100000;  */  	//Ödevde istenmediði için iptal
	
}


void print_histogram(int p, int num_sample){                                                										//PRINT HISTOGRAM FUNC.
	
	int i;
	int percent = ( ( p * 100) / num_sample);       //Yuzde hesaplama

	printf("%d\t", p);
	for( i=0; i<percent; i++){                      //'*' yazdýrma
		printf("*");
	}
	printf(" %% %d", percent);                      //Yuzde yazdýrma
	puts("");
}


int take_samples (int seed, int *counter1_100, int *counter101_200, int *counter201_300, int *counter301_400, int *counter401_500){       //RANGE SAYAÇ FUNC.
	
	if( (seed % 500) + 1 >= 1 && (seed % 500) + 1 <= 100 )								
		*counter1_100 += 1;
	else if( (seed % 500) + 1 >= 101 && (seed % 500) + 1 <= 200 )					
		 *counter101_200 += 1;
	else if( (seed % 500) + 1 >= 201 && (seed % 500) + 1 <= 300 )							
		 *counter201_300 += 1;
	else if( (seed % 500) + 1 >= 301 && (seed % 500) + 1 <= 400 )						
		 *counter301_400 += 1;
	else if( (seed % 500) + 1 >= 401 && (seed % 500) + 1 <= 500 )							
		 *counter401_500 += 1;
		 
}


